/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QrRewardsRouteImport } from './routes/qr-rewards'
import { Route as PersonalizeRouteImport } from './routes/personalize'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AirtimeRouteImport } from './routes/airtime'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRewardsRoute = QrRewardsRouteImport.update({
  id: '/qr-rewards',
  path: '/qr-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizeRoute = PersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AirtimeRoute = AirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airtime': typeof AirtimeRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/generating': typeof GeneratingRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/personalize': typeof PersonalizeRoute
  '/qr-rewards': typeof QrRewardsRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/upgrade': typeof UpgradeRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airtime': typeof AirtimeRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/generating': typeof GeneratingRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/personalize': typeof PersonalizeRoute
  '/qr-rewards': typeof QrRewardsRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/upgrade': typeof UpgradeRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airtime': typeof AirtimeRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/generating': typeof GeneratingRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/personalize': typeof PersonalizeRoute
  '/qr-rewards': typeof QrRewardsRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/upgrade': typeof UpgradeRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airtime'
    | '/confirm-email'
    | '/dashboard'
    | '/generating'
    | '/loading'
    | '/login'
    | '/notifications'
    | '/payment'
    | '/personalize'
    | '/qr-rewards'
    | '/signup'
    | '/spin'
    | '/upgrade'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airtime'
    | '/confirm-email'
    | '/dashboard'
    | '/generating'
    | '/loading'
    | '/login'
    | '/notifications'
    | '/payment'
    | '/personalize'
    | '/qr-rewards'
    | '/signup'
    | '/spin'
    | '/upgrade'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/airtime'
    | '/confirm-email'
    | '/dashboard'
    | '/generating'
    | '/loading'
    | '/login'
    | '/notifications'
    | '/payment'
    | '/personalize'
    | '/qr-rewards'
    | '/signup'
    | '/spin'
    | '/upgrade'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirtimeRoute: typeof AirtimeRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  DashboardRoute: typeof DashboardRoute
  GeneratingRoute: typeof GeneratingRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentRoute: typeof PaymentRoute
  PersonalizeRoute: typeof PersonalizeRoute
  QrRewardsRoute: typeof QrRewardsRoute
  SignupRoute: typeof SignupRoute
  SpinRoute: typeof SpinRoute
  UpgradeRoute: typeof UpgradeRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-rewards': {
      id: '/qr-rewards'
      path: '/qr-rewards'
      fullPath: '/qr-rewards'
      preLoaderRoute: typeof QrRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalize': {
      id: '/personalize'
      path: '/personalize'
      fullPath: '/personalize'
      preLoaderRoute: typeof PersonalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airtime': {
      id: '/airtime'
      path: '/airtime'
      fullPath: '/airtime'
      preLoaderRoute: typeof AirtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirtimeRoute: AirtimeRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  DashboardRoute: DashboardRoute,
  GeneratingRoute: GeneratingRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentRoute: PaymentRoute,
  PersonalizeRoute: PersonalizeRoute,
  QrRewardsRoute: QrRewardsRoute,
  SignupRoute: SignupRoute,
  SpinRoute: SpinRoute,
  UpgradeRoute: UpgradeRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
